name: Rancher Backup Agent
description: |
  Rancher Backup Agent
version: v1.0.1
category: Backup
maintainer: O.S. Systems
projectURL: http://github.com/OSSystems/rancher-backup-agent
labels:
  io.rancher.orchestration.supported: 'cattle'
