name: REX-Ray DigitalOcean
description: |
  Docker volume plugin for DigitalOcean
version: v0.0.0
category: Storage
maintainer: O.S. Systems
projectURL: http://github.com/OSSystems/rancher-catalog
labels:
  io.rancher.orchestration.supported: 'cattle,swarm'
