.catalog:
  name: "REX-Ray DigitalOcean"
  version: "v0.0.0"
  description: |
    Docker volume plugin for DigitalOcean
  questions:
    - variable: DOBS_TOKEN
      type: string
      required: true
      label: DigitalOcean Token
      description: DigitalOcean access token
    - variable: DOBS_REGION
      type: enum
      required: true
      label: DigitalOcean Region
      description: DigitalOcean region where volumes should be created
      default: nyc1
      options:
      - nyc1
      - sfo2
      - fra1
      - sgp1
    - variable: DEFAULT_VOLUME_SIZE
      type: int
      required: true
      default: 1
      label: DigitalOcean default volume size
      description: Size in GB to create volumes in DigitalOcean
    - variable: PLUGIN_HOST_INCLUDE
      type: string
      required: false
      label: "Include hosts"
      description: "Enable REX-Ray Docker volume plugin for hosts with a specific label"
    - variable: PLUGIN_HOST_EXCLUDE
      type: string
      required: false
      label: "Exclude hosts"
      description: "Disable REX-Ray Docker volume plugin for hosts with a specific label"

dobs:
  storage_driver:
    name: rexray-dobs
    scope: environment
    volume_access_mode: singleHostRW
