rexray:
  image: ossystems/rexray:0.9.0
  stdin_open: true
  tty: true
  environment:
    REXRAY_SERVICE_MODE: 'true'
    REXRAY_PROVIDER: 'dobs'
    DOBS_TOKEN: '${DOBS_TOKEN}'
    DOBS_REGION: '${DOBS_REGION}'
    DEFAULT_VOLUME_SIZE: '${DEFAULT_VOLUME_SIZE}'
  labels:
    io.rancher.container.pull_image: always

dobs:
  image: ossystems/rexray:0.9.0
  privileged: true
  stdin_open: true
  tty: true
  links:
    - rexray
  volumes:
    - /dev:/host/dev
    - /var/run/docker:/var/run/docker
    - /var/run/docker.sock:/var/run/docker.sock
    - /var/lib/docker:/var/lib/docker
    - /var/lib/rancher/volumes:/var/lib/rancher/volumes:shared
  environment:
    REXRAY_PROVIDER: 'dobs'
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.global: true
    io.rancher.scheduler.affinity:host_label: '${PLUGIN_HOST_INCLUDE}'
    io.rancher.scheduler.affinity:host_label_ne: '${PLUGIN_HOST_EXCLUDE}'
